# SPDX-FileCopyrightText: 2019 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# SPDX-FileCopyrightText: 2022 Henri Rosten
#
# SPDX-License-Identifier: GPL-2.0-only

matrix:
  include:

    # Sub-dir: development-process/stable-maintenance/regression-analysis/
    # Python version: 3.6
    - language: python
      python:
        - "3.6"
      before_install:
        - cd development-process/stable-maintenance/regression-analysis/
      install:
        - make install-requirements
      script:
        - make pre-push

    # Sub-dir: development-process/stable-maintenance/regression-analysis/
    # Python version: 3.7
    - language: python
      python:
        - "3.7"
      before_install:
        - cd development-process/stable-maintenance/regression-analysis/
      install:
        - pip install --upgrade importlib_metadata
        - make install-requirements
      script:
        - make pre-push

    # Sub-dir safety-architecture/tools/callgraph-tool
    # Python version: 3.6
    - language: python
      dist: bionic
      addons:
          apt:
              packages:
                  - build-essential
                  - cmake
                  - libstdc++-8-dev
                  - clang-10
                  - python3-clang-10
                  - llvm-10
                  - llvm-10-dev
                  - clang-format-10
                  - graphviz
      python:
        - "3.6"
      before_install:
        - cd safety-architecture/tools/callgraph-tool
      install:
        - make install-requirements
      script:
        - make pre-push

    # Sub-dir safety-architecture/tools/callgraph-tool
    # Python version: 3.7
    - language: python
      dist: bionic
      addons:
          apt:
              packages:
                  - build-essential
                  - cmake
                  - libstdc++-8-dev
                  - clang-10
                  - python3-clang-10
                  - llvm-10
                  - llvm-10-dev
                  - clang-format-10
                  - graphviz
      python:
        - "3.7"
      before_install:
        - cd safety-architecture/tools/callgraph-tool
      install:
        - make install-requirements
      script:
        - make pre-push
