# SPDX-FileCopyrightText: 2020 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
# SPDX-License-Identifier: Apache-2.0

Direct:
  # System calls
  read:
    __x64_sys_read
  write:
    __x64_sys_write
  open:
    __x64_sys_open
  close:
    __x64_sys_close
  stat:
    __x64_sys_newstat
  fstat:
    __x64_sys_newfstat
  lstat:
    __x64_sys_newlstat
  poll:
    __x64_sys_poll
  lseek:
    __x64_sys_lseek
  mmap:
    __x64_sys_mmap
  mprotect:
    __x64_sys_mprotect
  munmap:
    __x64_sys_munmap
  brk:
    __x64_sys_brk
  rt_sigaction:
    __x64_sys_rt_sigaction
  rt_sigprocmask:
    __x64_sys_rt_sigprocmask
  rt_sigreturn:
    __x64_sys_rt_sigreturn
  ioctl:
    __x64_sys_ioctl
  pread64:
    __x64_sys_pread64
  pwrite64:
    __x64_sys_pwrite64
  readv:
    __x64_sys_readv
  writev:
    __x64_sys_writev
  access:
    __x64_sys_access
  pipe:
    __x64_sys_pipe
  select:
    __x64_sys_select
  sched_yield:
    __x64_sys_sched_yield
  mremap:
    __x64_sys_mremap
  msync:
    __x64_sys_msync
  mincore:
    __x64_sys_mincore
  madvise:
    __x64_sys_madvise
  shmget:
    __x64_sys_shmget
  shmat:
    __x64_sys_shmat
  shmctl:
    __x64_sys_shmctl
  dup:
    __x64_sys_dup
  dup2:
    __x64_sys_dup2
  pause:
    __x64_sys_pause
  nanosleep:
    __x64_sys_nanosleep
  getitimer:
    __x64_sys_getitimer
  alarm:
    __x64_sys_alarm
  setitimer:
    __x64_sys_setitimer
  getpid:
    __x64_sys_getpid
  sendfile:
    __x64_sys_sendfile64
  socket:
    __x64_sys_socket
  connect:
    __x64_sys_connect
  accept:
    __x64_sys_accept
  sendto:
    __x64_sys_sendto
  recvfrom:
    __x64_sys_recvfrom
  sendmsg:
    __x64_sys_sendmsg
  recvmsg:
    __x64_sys_recvmsg
  shutdown:
    __x64_sys_shutdown
  bind:
    __x64_sys_bind
  listen:
    __x64_sys_listen
  getsockname:
    __x64_sys_getsockname
  getpeername:
    __x64_sys_getpeername
  socketpair:
    __x64_sys_socketpair
  setsockopt:
    __x64_sys_setsockopt
  getsockopt:
    __x64_sys_getsockopt
  clone:
    __x64_sys_clone
  fork:
    __x64_sys_fork
  vfork:
    __x64_sys_vfork
  execve:
    __x64_sys_execve
  exit:
    __x64_sys_exit
  wait4:
    __x64_sys_wait4
  kill:
    __x64_sys_kill
  uname:
    __x64_sys_newuname
  semget:
    __x64_sys_semget
  semop:
    __x64_sys_semop
  semctl:
    __x64_sys_semctl
  shmdt:
    __x64_sys_shmdt
  msgget:
    __x64_sys_msgget
  msgsnd:
    __x64_sys_msgsnd
  msgrcv:
    __x64_sys_msgrcv
  msgctl:
    __x64_sys_msgctl
  fcntl:
    __x64_sys_fcntl
  flock:
    __x64_sys_flock
  fsync:
    __x64_sys_fsync
  fdatasync:
    __x64_sys_fdatasync
  truncate:
    __x64_sys_truncate
  ftruncate:
    __x64_sys_ftruncate
  getdents:
    __x64_sys_getdents
  getcwd:
    __x64_sys_getcwd
  chdir:
    __x64_sys_chdir
  fchdir:
    __x64_sys_fchdir
  rename:
    __x64_sys_rename
  mkdir:
    __x64_sys_mkdir
  rmdir:
    __x64_sys_rmdir
  creat:
    __x64_sys_creat
  link:
    __x64_sys_link
  unlink:
    __x64_sys_unlink
  symlink:
    __x64_sys_symlink
  readlink:
    __x64_sys_readlink
  chmod:
    __x64_sys_chmod
  fchmod:
    __x64_sys_fchmod
  chown:
    __x64_sys_chown
  fchown:
    __x64_sys_fchown
  lchown:
    __x64_sys_lchown
  umask:
    __x64_sys_umask
  gettimeofday:
    __x64_sys_gettimeofday
  getrlimit:
    __x64_sys_getrlimit
  getrusage:
    __x64_sys_getrusage
  sysinfo:
    __x64_sys_sysinfo
  times:
    __x64_sys_times
  ptrace:
    __x64_sys_ptrace
  getuid:
    __x64_sys_getuid
  syslog:
    __x64_sys_syslog
  getgid:
    __x64_sys_getgid
  setuid:
    __x64_sys_setuid
  setgid:
    __x64_sys_setgid
  geteuid:
    __x64_sys_geteuid
  getegid:
    __x64_sys_getegid
  setpgid:
    __x64_sys_setpgid
  getppid:
    __x64_sys_getppid
  getpgrp:
    __x64_sys_getpgrp
  setsid:
    __x64_sys_setsid
  setreuid:
    __x64_sys_setreuid
  setregid:
    __x64_sys_setregid
  getgroups:
    __x64_sys_getgroups
  setgroups:
    __x64_sys_setgroups
  setresuid:
    __x64_sys_setresuid
  getresuid:
    __x64_sys_getresuid
  setresgid:
    __x64_sys_setresgid
  getresgid:
    __x64_sys_getresgid
  getpgid:
    __x64_sys_getpgid
  setfsuid:
    __x64_sys_setfsuid
  setfsgid:
    __x64_sys_setfsgid
  getsid:
    __x64_sys_getsid
  capget:
    __x64_sys_capget
  capset:
    __x64_sys_capset
  rt_sigpending:
    __x64_sys_rt_sigpending
  rt_sigtimedwait:
    __x64_sys_rt_sigtimedwait
  rt_sigqueueinfo:
    __x64_sys_rt_sigqueueinfo
  rt_sigsuspend:
    __x64_sys_rt_sigsuspend
  sigaltstack:
    __x64_sys_sigaltstack
  utime:
    __x64_sys_utime
  mknod:
    __x64_sys_mknod
  personality:
    __x64_sys_personality
  ustat:
    __x64_sys_ustat
  statfs:
    __x64_sys_statfs
  fstatfs:
    __x64_sys_fstatfs
  sysfs:
    __x64_sys_sysfs
  getpriority:
    __x64_sys_getpriority
  setpriority:
    __x64_sys_setpriority
  sched_setparam:
    __x64_sys_sched_setparam
  sched_getparam:
    __x64_sys_sched_getparam
  sched_setscheduler:
    __x64_sys_sched_setscheduler
  sched_getscheduler:
    __x64_sys_sched_getscheduler
  sched_get_priority_max:
    __x64_sys_sched_get_priority_max
  sched_get_priority_min:
    __x64_sys_sched_get_priority_min
  sched_rr_get_interval:
    __x64_sys_sched_rr_get_interval
  mlock:
    __x64_sys_mlock
  munlock:
    __x64_sys_munlock
  mlockall:
    __x64_sys_mlockall
  munlockall:
    __x64_sys_munlockall
  vhangup:
    __x64_sys_vhangup
  modify_ldt:
    __x64_sys_modify_ldt
  pivot_root:
    __x64_sys_pivot_root
  _sysctl:
    __x64_sys_sysctl
  prctl:
    __x64_sys_prctl
  arch_prctl:
    __x64_sys_arch_prctl
  adjtimex:
    __x64_sys_adjtimex
  setrlimit:
    __x64_sys_setrlimit
  chroot:
    __x64_sys_chroot
  sync:
    __x64_sys_sync
  acct:
    __x64_sys_acct
  settimeofday:
    __x64_sys_settimeofday
  mount:
    __x64_sys_mount
  umount2:
    __x64_sys_umount
  swapon:
    __x64_sys_swapon
  swapoff:
    __x64_sys_swapoff
  reboot:
    __x64_sys_reboot
  sethostname:
    __x64_sys_sethostname
  setdomainname:
    __x64_sys_setdomainname
  iopl:
    __x64_sys_iopl
  ioperm:
    __x64_sys_ioperm
  init_module:
    __x64_sys_init_module
  delete_module:
    __x64_sys_delete_module
  quotactl:
    __x64_sys_quotactl
  gettid:
    __x64_sys_gettid
  readahead:
    __x64_sys_readahead
  setxattr:
    __x64_sys_setxattr
  lsetxattr:
    __x64_sys_lsetxattr
  fsetxattr:
    __x64_sys_fsetxattr
  getxattr:
    __x64_sys_getxattr
  lgetxattr:
    __x64_sys_lgetxattr
  fgetxattr:
    __x64_sys_fgetxattr
  listxattr:
    __x64_sys_listxattr
  llistxattr:
    __x64_sys_llistxattr
  flistxattr:
    __x64_sys_flistxattr
  removexattr:
    __x64_sys_removexattr
  lremovexattr:
    __x64_sys_lremovexattr
  fremovexattr:
    __x64_sys_fremovexattr
  tkill:
    __x64_sys_tkill
  time:
    __x64_sys_time
  futex:
    __x64_sys_futex
  sched_setaffinity:
    __x64_sys_sched_setaffinity
  sched_getaffinity:
    __x64_sys_sched_getaffinity
  io_setup:
    __x64_sys_io_setup
  io_destroy:
    __x64_sys_io_destroy
  io_getevents:
    __x64_sys_io_getevents
  io_submit:
    __x64_sys_io_submit
  io_cancel:
    __x64_sys_io_cancel
  lookup_dcookie:
    __x64_sys_lookup_dcookie
  epoll_create:
    __x64_sys_epoll_create
  remap_file_pages:
    __x64_sys_remap_file_pages
  getdents64:
    __x64_sys_getdents64
  set_tid_address:
    __x64_sys_set_tid_address
  restart_syscall:
    __x64_sys_restart_syscall
  semtimedop:
    __x64_sys_semtimedop
  fadvise64:
    __x64_sys_fadvise64
  timer_create:
    __x64_sys_timer_create
  timer_settime:
    __x64_sys_timer_settime
  timer_gettime:
    __x64_sys_timer_gettime
  timer_getoverrun:
    __x64_sys_timer_getoverrun
  timer_delete:
    __x64_sys_timer_delete
  clock_settime:
    __x64_sys_clock_settime
  clock_gettime:
    __x64_sys_clock_gettime
  clock_getres:
    __x64_sys_clock_getres
  clock_nanosleep:
    __x64_sys_clock_nanosleep
  exit_group:
    __x64_sys_exit_group
  epoll_wait:
    __x64_sys_epoll_wait
  epoll_ctl:
    __x64_sys_epoll_ctl
  tgkill:
    __x64_sys_tgkill
  utimes:
    __x64_sys_utimes
  mbind:
    __x64_sys_mbind
  set_mempolicy:
    __x64_sys_set_mempolicy
  get_mempolicy:
    __x64_sys_get_mempolicy
  mq_open:
    __x64_sys_mq_open
  mq_unlink:
    __x64_sys_mq_unlink
  mq_timedsend:
    __x64_sys_mq_timedsend
  mq_timedreceive:
    __x64_sys_mq_timedreceive
  mq_notify:
    __x64_sys_mq_notify
  mq_getsetattr:
    __x64_sys_mq_getsetattr
  kexec_load:
    __x64_sys_kexec_load
  waitid:
    __x64_sys_waitid
  add_key:
    __x64_sys_add_key
  request_key:
    __x64_sys_request_key
  keyctl:
    __x64_sys_keyctl
  ioprio_set:
    __x64_sys_ioprio_set
  ioprio_get:
    __x64_sys_ioprio_get
  inotify_init:
    __x64_sys_inotify_init
  inotify_add_watch:
    __x64_sys_inotify_add_watch
  inotify_rm_watch:
    __x64_sys_inotify_rm_watch
  migrate_pages:
    __x64_sys_migrate_pages
  openat:
    __x64_sys_openat
  mkdirat:
    __x64_sys_mkdirat
  mknodat:
    __x64_sys_mknodat
  fchownat:
    __x64_sys_fchownat
  futimesat:
    __x64_sys_futimesat
  newfstatat:
    __x64_sys_newfstatat
  unlinkat:
    __x64_sys_unlinkat
  renameat:
    __x64_sys_renameat
  linkat:
    __x64_sys_linkat
  symlinkat:
    __x64_sys_symlinkat
  readlinkat:
    __x64_sys_readlinkat
  fchmodat:
    __x64_sys_fchmodat
  faccessat:
    __x64_sys_faccessat
  pselect6:
    __x64_sys_pselect6
  ppoll:
    __x64_sys_ppoll
  unshare:
    __x64_sys_unshare
  set_robust_list:
    __x64_sys_set_robust_list
  get_robust_list:
    __x64_sys_get_robust_list
  splice:
    __x64_sys_splice
  tee:
    __x64_sys_tee
  sync_file_range:
    __x64_sys_sync_file_range
  vmsplice:
    __x64_sys_vmsplice
  move_pages:
    __x64_sys_move_pages
  utimensat:
    __x64_sys_utimensat
  epoll_pwait:
    __x64_sys_epoll_pwait
  signalfd:
    __x64_sys_signalfd
  timerfd_create:
    __x64_sys_timerfd_create
  eventfd:
    __x64_sys_eventfd
  fallocate:
    __x64_sys_fallocate
  timerfd_settime:
    __x64_sys_timerfd_settime
  timerfd_gettime:
    __x64_sys_timerfd_gettime
  accept4:
    __x64_sys_accept4
  signalfd4:
    __x64_sys_signalfd4
  eventfd2:
    __x64_sys_eventfd2
  epoll_create1:
    __x64_sys_epoll_create1
  dup3:
    __x64_sys_dup3
  pipe2:
    __x64_sys_pipe2
  inotify_init1:
    __x64_sys_inotify_init1
  preadv:
    __x64_sys_preadv
  pwritev:
    __x64_sys_pwritev
  rt_tgsigqueueinfo:
    __x64_sys_rt_tgsigqueueinfo
  perf_event_open:
    __x64_sys_perf_event_open
  recvmmsg:
    __x64_sys_recvmmsg
  fanotify_init:
    __x64_sys_fanotify_init
  fanotify_mark:
    __x64_sys_fanotify_mark
  prlimit64:
    __x64_sys_prlimit64
  name_to_handle_at:
    __x64_sys_name_to_handle_at
  open_by_handle_at:
    __x64_sys_open_by_handle_at
  clock_adjtime:
    __x64_sys_clock_adjtime
  syncfs:
    __x64_sys_syncfs
  sendmmsg:
    __x64_sys_sendmmsg
  setns:
    __x64_sys_setns
  getcpu:
    __x64_sys_getcpu
  process_vm_readv:
    __x64_sys_process_vm_readv
  process_vm_writev:
    __x64_sys_process_vm_writev
  kcmp:
    __x64_sys_kcmp
  finit_module:
    __x64_sys_finit_module
  sched_setattr:
    __x64_sys_sched_setattr
  sched_getattr:
    __x64_sys_sched_getattr
  renameat2:
    __x64_sys_renameat2
  seccomp:
    __x64_sys_seccomp
  getrandom:
    __x64_sys_getrandom
  memfd_create:
    __x64_sys_memfd_create
  kexec_file_load:
    __x64_sys_kexec_file_load
  bpf:
    __x64_sys_bpf
  execveat:
    __x64_sys_execveat
  userfaultfd:
    __x64_sys_userfaultfd
  membarrier:
    __x64_sys_membarrier
  mlock2:
    __x64_sys_mlock2
  copy_file_range:
    __x64_sys_copy_file_range
  preadv2:
    __x64_sys_preadv2
  pwritev2:
    __x64_sys_pwritev2
  pkey_mprotect:
    __x64_sys_pkey_mprotect
  pkey_alloc:
    __x64_sys_pkey_alloc
  pkey_free:
    __x64_sys_pkey_free
  statx:
    __x64_sys_statx
  io_pgetevents:
    __x64_sys_io_pgetevents
  rseq:
    __x64_sys_rseq

  # Generic
  start_kernel:
    start_kernel

  # Interrupts
  sdhci_irq:
    - sdhci_irq
    - sdhci_thread_irq
  regmap_irq:
    - regmap_irq_thread
  lineevent_irq:
    - lineevent_irq_handler
    - lineevent_irq_thread
  proc_thermal_pci_msi_irq:
    - proc_thermal_pci_msi_irq
  rt5645_irq:
    - rt5645_irq
  rt286_irq:
    - rt286_irq
  intel_soc_thermal_irq:
    - soc_irq_thread_fn
  skl_interrupt:
    - skl_interrupt
    - skl_threaded_handler
  rt298_i2c_irq:
    - rt298_irq
  gpio_trig_gpio_irq:
    - gpio_trig_irq
  dev_pm_dedicated_wake_irq:
    - handle_threaded_wake_irq
  sst_dsp_irq:
    - sst_dsp_new
  mei_txe_pci_irq:
    - mei_txe_irq_thread_handler
  mei_me_irq:
    - mei_me_irq_quick_handler
    - mei_me_irq_thread_handler
  da7219_aad_irq:
    - da7219_aad_irq_thread
  wm8903_irq:
    - wm8903_irq
  snd_ca0106_irq:
    - snd_ca0106_interrupt
  xhci_msix_irq:
    - xhci_msi_irq
  snd_mpu401_uart_irq:
    - snd_mpu401_uart_interrupt
  bnx2x_msix_irq:
    - bnx2x_msix_sp_int
  tg3_test_irq:
    - tg3_test_isr
  i40e_vsi_irq:
    - i40e_intr
  e100_irq:
    - e100_intr
  acpi_os_irq:
    - acpi_irq
  bnx2x_irq:
    - bnx2x_interrupt
  snd_cmipci_irq:
    - snd_cmipci_interrupt
  snd_emu10k1_irq:
    - snd_emu10k1_interrupt
  igb_intr_test_irq:
    - igb_test_intr
  snd_ice1712_irq:
    - snd_ice1712_interrupt
  igb_irq:
    - igb_intr_msi
  serial8250_link_chain_irq:
    - serial8250_interrupt
  vp_vqs_msix_vring_irq:
    - vring_interrupt
  hpet_ioctl_ieon_irq:
    - hpet_interrupt
  fd_floppy_irq:
    - floppy_hardint
  xhci_msi_irq:
    - xhci_msi_irq
  e1000_test_msi_irq:
    - e1000_intr_msi_test
  dmar_irq:
    - dmar_fault
  snd_rme9652_irq:
    - snd_rme9652_interrupt
  rtl8139_irq:
    - rtl8139_interrupt
  hpet_irq:
    - hpet_interrupt_handler
  e1000_msix_irq:
    - e1000_intr_msix_rx
  snd_rme96_irq:
    - snd_rme96_interrupt
  parport_irq:
    - parport_irq_handler
  aer_irq:
    - aer_irq
  i8042_irq:
    - i8042_interrupt
  cmos_irq:
    - cmos_interrupt
  pxa2xx_spi_ssp_irq:
    - ssp_int
  i40e_irq:
    - i40e_intr
  pnp_check_irq:
    - pnp_test_handler
  xhci_msi_usb_hcd_irq:
    - usb_hcd_irq
  vm_vqs_irq:
    - vm_interrupt
  i8042_check_aux_irq:
    - i8042_aux_test_irq
  snd_intel8x0_irq:
    - snd_intel8x0_interrupt
  snd_emu10k1x_irq:
    - snd_emu10k1x_interrupt
  snd_hdspm_irq:
    - snd_hdspm_interrupt
  i8042_kbd_irq:
    - i8042_interrupt
  uio_irq:
    - uio_interrupt
  igbvf_msix_irq:
    - igbvf_intr_msix_tx
  vp_find_vqs_irq:
    - vp_interrupt
  snd_hdsp_irq:
    - snd_hdsp_interrupt
  e1000_intr_test_irq:
    - e1000_test_intr
  i40evf_msix_irq:
    - i40evf_msix_aq
  oxygen_pci_irq:
    - oxygen_interrupt
  igb_msix_irq:
    - igb_msix_other
  snd_vt1724_irq:
    - snd_vt1724_interrupt
  cp_irq:
    - cp_interrupt
  hsu_pci_irq:
    - hsu_pci_irq
  sdhci_pci_sd_cd_irq:
    - sdhci_pci_sd_cd
  dw_dma_irq:
    - dw_dma_interrupt
  i40evf_traffic_irq:
    - i40evf_msix_clean_rings
  pcie_pme_irq:
    - pcie_pme_irq
  snd_atiixp_irq:
    - snd_atiixp_interrupt
  usb_hcd_irq:
    - usb_hcd_irq
  ct_20k2_hw_card_irq:
    - ct_20k2_interrupt
  azx_irq:
    - azx_interrupt
  snd_soc_jack_gpio_irq:
    - gpio_handler
  gpio_sysfs_irq:
    - gpio_sysfs_irq
  smbus_alert_irq:
    - smbus_alert
  usb_phy_generic_gpio_vbus_irq:
    - nop_gpio_vbus_thread
  ts3a227e_i2c_irq:
    - ts3a227e_interrupt
  max98090_i2c_irq:
    - max98090_interrupt
  nau8825_irq:
    - nau8825_interrupt
  wm8962_i2c_irq:
    - wm8962_irq
  cs35l33_i2c_irq:
    - cs35l33_irq_thread
  intel_gpio_irq:
    - intel_gpio_irq
  ipc_pci_ioc_irq:
    - ioc
  i801_irq:
    - i801_isr
  intel_punit_ipc_irq:
    - intel_punit_ioc
    - punit_ipcdev
  idma64_irq:
    - idma64_irq
  dwc2_irq:
    - dwc2_handle_common_intr
  i2c_dw_irq:
    - i2c_dw_isr
  ipc_plat_probe_irq:
    - ioc
    - ipcdev
  ahci_host_multi_irq:
    - ahci_multi_irqs_intr_hard
  vrtc_mrst_irq:
    - mrst_rtc_irq
  tpm_tis_irq:
    - tis_int_handler
  ismt_irq:
    - ismt_do_msi_interrupt
  ipc_ioc_irq:
    - ioc
  rt5651_i2c_irq:
    - rt5651_irq
  ioat_dma_irq:
    - ioat_dma_do_interrupt_msix
  acp_audio_dma_irq:
    - dma_irq_handler
  rt5640_i2c_irq:
    - rt5640_irq
  nvme_irq:
    - nvme_irq_check
    - nvme_irq
  rtl8169_irq:
    - rtl8169_interrupt
  hrtimer_run_softirq:
    - __hrtimer_run_queues
TriggerMapIgnore:
  - do_current_softirqs
  - notifier_call_chain
